# Generated by Django 5.2.4 on 2025-08-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_post_uploaded_file_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="files/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="uploaded_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
